[book]
authors = ["d0UBleW"]
language = "en"
src = "src"
title = "d0ublew's Blog"
description = "An average blog consisting of CTF writeups and notes"

[build]
build-dir = "book"                # the directory where the output is placed
create-missing = true             # whether or not to create missing pages
use-default-preprocessors = true  # use the default preprocessors
extra-watch-dirs = []             # directories to watch for triggering builds

[preprocessor]

[preprocessor.index]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-css = ["./theme/catppuccin.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
default-theme = "light"
preferred-dark-theme = "ayu"
no-section-label = true
git-repository-url = "https://github.com/d0UBleW/d0ublew.github.io"
# git-repository-icon = "fa-github"
mathjax-support = true

[output.html.fold]
enable = false
